exp:
  dir: /root/workspace/logs/beef/hdd_driver_only
  resume: null
dataset:
  import: datasets.factory
  name: hdd_classif
  dir_data: /datasets_local/HDD
  train_split: train
  eval_split: val
  nb_threads: 6
  batch_size: 12
  debug: false
  fps: 3
  horizon: 2
  im_size: small
  win_size: 21
  layer: cause
  frame_position: 20
  traintest_mode: true
model:
  name: default
  network:
    inputs_opt:
      img: true
      prev_points: true
      blinkers: true
    import: models.networks.factory
    name: driver_hdd
    blinkers_dim: 32
    n_future: 13
    gru_opt:
      hidden_size: 256
      num_layers: 1
      dropout: 0.0
  criterion:
    import: models.criterions.factory
    name: l2_points
    future_only: false
    use_mae: false
    fix_loss: true
  metric:
    import: models.metrics.factory
    name: future_traj
misc:
  logs_name: null
  cuda: true
  seed: 1337
engine:
  name: logger
  debug: false
  print_freq: 10
  nb_epochs: 1
  saving_criteria:
  - eval_epoch.loss:min
  - eval_epoch.future_mse:min
view:
  import: views.factory
  name: plotly
  plot_width: 4096
  items:
  - logs:train_epoch.loss+logs:eval_epoch.loss
  - logs:train_epoch.future_mse+logs:eval_epoch.future_mse
optimizer:
  name: adam
  lr: 0.0001
  momentum: 0.99
